version: '2.2'

services:
  mysql:
    image: mysql:latest
    volumes:
      - /leon/mysql/mydir:/mydir
      - /leon/mysql/datadir:/var/lib/mysql
      - /leon/mysql/conf/my.cnf:/etc/my.cnf
      #数据库还原目录 可将需要还原的sql文件放在这里
      - /leon/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=leon"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    mem_limit: 350m
  redis:
    image: redis:latest
    command: redis-server
    restart: "always"
    ports:
      - 6379:6379
    mem_limit: 120m
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: "always"
    user: root
    volumes:
      - /leon/jenkins_home:/var/jenkins_home
    ports:
      - 8090:8080
      - 50000:5000
    mem_limit: 800m