server:
  port: 9527
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.186.131/leon
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
  redis:
    host: 192.168.186.131
    port: 6379